Repository bradtaniguchi/discord-bot-test, pull requests merged in 2020-09, with the labels that each got.

#157 Feat/152/suspend user log
  src/APIs/mongo-suspend.ts
  src/commands/suspend.ts
  src/commands/user.ts
  src/db/collections.ts
  src/db/models.ts
  src/db/moderator.ts
  src/db/queries/create-new-user.ts
  src/db/queries/create-user-log.ts
  src/db/queries/create-user-suspension.ts
  src/db/queries/get-user-entries.ts
  src/db/queries/update-existing-identity.ts
  src/db/user-identity.ts
  src/db/user-log.ts
  src/db/user-suspension.ts
  src/db/user.ts
Labels: database, enhancement, migration

#145 Feat/119/update logger
  .eslintrc.js
  package-lock.json
  package.json
  src/commands/add-formatting.ts
  src/commands/bootstrap-commands.ts
  src/commands/close.ts
  src/commands/coc.ts
  src/commands/format.ts
  src/commands/forum.ts
  src/commands/quote.ts
  src/commands/stats.ts
  src/commands/suspend.ts
  src/commands/user.ts
  src/config/validate-config.ts
  src/index.ts
  src/reactions/bootstrap-reactions.ts
  src/reactions/format-reaction.ts
  src/reactions/pin.ts
  src/utilities/logger.ts
Labels: enhancement, migration

#179 Add message.send to error handling
  src/commands/close.ts
  src/commands/format.ts
  src/commands/suspend.ts
  src/commands/user.ts
Labels: chore, migration

#178 Automatically add issue and PR embeds
  package-lock.json
  package.json
  src/APIs/github-def.ts
  src/commands/bootstrap-commands.ts
  src/config/get-config.ts
  src/listeners/issue-embedder.ts
  src/utilities/get-issue-data.ts
  src/utilities/get-issue-numbers.ts
  src/utilities/issue-embed-generator.ts
Labels: feature, migration

#185 Replace mod handbook links
  README.md
  src/commands/mod.ts
Labels: chore, documentation, migration
