Repository bradtaniguchi/discord-bot-test, pull requests merged in 2020-05, with the labels that each got.

#4 Add some documentation
  README.md
Labels: documentation

#29 Fix ESLint and Prettier rule clashing
  .eslintrc.js
  .prettierrc
  package-lock.json
  package.json
  src/commands/bootstrap.js
  src/commands/eightball.js
  src/commands/help.js
  src/config/get-config.js
Labels: bug

#31 Update prefix passing, get-config return
  src/commands/bootstrap.js
  src/config/get-config.js
  src/index.js
Labels: enhancement

#27 Add format command to the bot
  package-lock.json
  package.json
  src/commands/add-formatting.js
  src/index.js
  src/utilities/confused-message-generator.js
  src/utilities/format-codeblock.js
  src/utilities/formatter.js
  src/utilities/is-suppoted-by-prettier.js
  src/utilities/process-reply.js
Labels: feature
