Repository bradtaniguchi/discord-bot-test, pull requests merged in 2020-08, with the labels that each got.

#128 Feature/radio integration
  package-lock.json
  package.json
  src/commands/commands.ts
  src/commands/radio.ts
Labels: feature, work in progress

#141 Add tests for some utility functions
  src/tests/bot-online-time.test.ts
  src/tests/format-codeblock.test.ts
  src/tests/formatter.test.ts
  src/tests/is-supported-by-prettier.test.ts
  src/utilities/formatter.ts
Labels: enhancement

#163 Chore/125/badges
  README.md
Labels: chore
